[Unit]
StartLimitIntervalSec=0

[Service]
Environment="LD_PRELOAD=/usr/local/lib/smiusb/libsmiusb_guard.so" "SMIUSB_GUARD_RESTART_ON_DISCONNECT=1"
Restart=always
RestartSec=500ms
KillSignal=SIGKILL
SuccessExitStatus=SIGKILL
